-- CreateTable
CREATE TABLE "BaseFund" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "cashPortion" INTEGER NOT NULL DEFAULT 0,
    "nequiPortion" INTEGER NOT NULL DEFAULT 1110000,
    "updatedAt" DATETIME NOT NULL
);
